all: life life_debug validate life-memopt life_debug-memopt

life_debug: life.cpp submit.cpp 
	cilk++ -DDEBUG=1 -DALG=0 -fcilkscreen -o life_debug life.cpp submit.cpp 

life: life.cpp submit.cpp
	cilk++ -DDEBUG=0 -DALG=0 -fcilkscreen -o life life.cpp submit.cpp 

life_debug-memopt: life.cpp submit.cpp 
	cilk++ -DDEBUG=1 -DALG=1 -fcilkscreen -o life_debug-memopt life.cpp submit.cpp 

life-memopt: life.cpp submit.cpp
	cilk++ -DDEBUG=0 -DALG=1 -fcilkscreen -o life-memopt life.cpp submit.cpp 

validate: validate.cpp
	g++ -o validate validate.cpp	
clean: 
	rm life validate
